# Generated by Django 5.1.4 on 2025-02-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset_Model',
            fields=[
                ('Data_id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(null=True, upload_to='media/')),
            ],
            options={
                'db_table': 'upload',
            },
        ),
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(null=True)),
                ('phonenumber', models.TextField(max_length=15)),
                ('address', models.TextField(max_length=254)),
                ('Image', models.FileField(null=True, upload_to='images/')),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
                ('user_status', models.TextField(default='pending', max_length=50, null=True)),
                ('otp', models.IntegerField(null=True)),
                ('otp_status', models.TextField(default='pending', max_length=60, null=True)),
                ('last_login_time', models.TimeField(auto_now_add=True, null=True)),
                ('last_login_date', models.DateField(auto_now_add=True, null=True)),
                ('numberoftimeslogin', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
